name: Run Unit Tests

on:
  push:
    branches:
    - '**'


jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///./testing/test.db"
      SUPABASE_URL: "https://github.com/noahdavis05/Web-Services-CWK1"
      SUPABASE_PUBLIC_KEY: "test-public"
      SUPABASE_SECRET_KEY: "test-secret"
      AUTHENTICATION_ON: "true"
      MCP_INTERNAL_KEY: "key"

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv 
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r api/requirements.txt 

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          cd api 
          pytest --disable-warnings
